#ifndef OPERATORS_H
#define OPERATORS_H

extern const char *operator_names[];

enum LispOperation {
    OP_QUOTE,
    OP_CAR,
    OP_CDR,
    OP_ATOM_Q,
    OP_EQ_Q,
    OP_CONS,
    OP_COND,

    OP_ASSOC,
    OP_SUBST,

    OP_PAIR_Q,
    OP_CHAR_Q,
    OP_BOOLEAN_Q,
    OP_STRING_Q,
    OP_NUMBER_Q,
    OP_INTEGER_Q,
    OP_REAL_Q,
    OP_INTEGER_REAL,
    OP_REAL_INTEGER,
    OP_INTEGER_CHAR,
    OP_CHAR_INTEGER,
    OP_NUMBER_STRING,
    OP_STRING_NUMBER,
    OP_STRING_DATA,
    OP_DATA_STRING,

    OP_DISPLAY,
    OP_NEWLINE,

    OP_PLUS,
    OP_MINUS,
    OP_TIMES,
    OP_DIVIDE,

    OP_LESS,
    OP_EQUAL,
    OP_BIGGER,
    OP_LESS_EQUAL,
    OP_BIGGER_EQUAL,

    OP_AND,
    OP_OR,
    OP_NOT,

    OP_BEGIN,
    OP_DEFINE,
    OP_SET_E,
    OP_EVAL,
    OP_LAMBDA,
    OP_MACRO,
    OP_CLOSURE,
    OP_APPLY,
    OP_READ,
    OP_WRITE,
    OP_CURRENT_ENVIRONMENT,

    OP_MEM_ALLOC,
    OP_MEM_READ,
    OP_MEM_WRITE,
    OP_MEM_FILL,
    OP_MEM_COPY,
    OP_MEM_ADDR,

    OP_LOAD,
    OP_UNLOAD,

    OP_VM_FIRST,
    OP_VM_NORMAL,
    OP_VM_QUOTE,
    OP_VM_COND,
    OP_VM_LOGIC,
    OP_VM_DEFINE,
    OP_VM_BEGIN,
    OP_VM_APPLY,
    OP_VM_EVAL,
    OP_VM_LOAD,
    OP_VM_CALL,
    OP_VM_EVAL_LIST
};

constexpr int NUMBER_BASIC_OPERATORS = OP_VM_EVAL_LIST + 1;

#endif /* OPERATORS_H */